FROM node:16.18.0 as build

WORKDIR /app-recette
COPY package*.json ./
RUN yarn cache clean && yarn --update-checksums
COPY . /app-recette/
RUN rm -rf node_modules
RUN apt-get -y install bash git
RUN yarn && yarn build

# Stage - Production
FROM nginx:1.17-alpine
COPY --from=build /app-recette/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
