version: '3.8'

services:
  app:
    container_name: challengebapp
    image: challengebapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app"
    ports:
      - 3000:3000